import type { TechTree, Countries } from '@/types/TankShells'

const WT_SKIN_BASE = "https://static.encyclopedia.warthunder.com/gui_skin";

const countryIconFile: Record<Countries, string> = {
  USA: "usa",
  Iran: "iran",
  Turkey: "turkey",
  Australia: "australia",
  Greece: "greece_modern",
  "Canada": "canada",
  "Republic of Vietnam": "south_vietnam",
  Norway: "norway",
  Philippines: "philippines",
  "Germany (modern)": "germany_modern",
  Poland: "poland",
  GDR: "gdr",
  "Canada (modern)": "canada_modern",
  Lithuania: "lithuania",
  "German Empire": "germany_empire",
  Spain: "spain",
  Finland: "finland",
  Germany: "germany",
  Romania: "romania",
  "South Africa (modern)": "south_africa_modern",
  Switzerland: "switzerland",
  Argentina: "argentina",
  USSR: "ussr",
  Cuba: "cuba",
  Venezuela: "venezuela",
  Russia: "russia",
  Syria: "syria",
  Slovakia: "slovakia",
  "Russian Empire": "russia_empire",
  "Czech Republic": "czech",
  Serbia: "lang_serbia",
  Kazakhstan: "kazakhstan",
  "Great Britain": "britain",
  India: "india",
  Jordan: "jordan",
  "South Africa": "south_africa",
  "New Zealand": "new_zealand",
  Ireland: "ireland",
  Kuwait: "kuwait",
  Japan: "japan",
  Indonesia: "indonesia",
  Malaysia: "malaysia",
  Thailand: "thailand",
  China: "china",
  Pakistan: "pakistan",
  Vietnam: "vietnam",
  "North Korea": "north_korea",
  Bangladesh: "bangladesh",
  Italy: "italy",
  "Kingdom of Italy": "",
  Hungary: "hungary",
  "Hungary (modern)": "hungary_modern",
  Oman: "oman",
  Portugal: "portugal",
  Brazil: "brazil",
  France: "france",
  Belgium: "belgium",
  Austria: "austria",
  Netherlands: "netherlands",
  Sweden: "sweden",
  Denmark: "denmark",
  Israel: "israel",
  Singapore: "singapore",
  Colombia: "colombia",
};

const techTreeFallback: Record<TechTree, string> = {
  USA: "usa",
  Germany: "germany",
  USSR: "ussr",
  "Great Britain": "britain",
  Japan: "japan",
  China: "china",
  Italy: "italy",
  France: "france",
  Sweden: "sweden",
  Israel: "israel",
};

export function getCountryIcons(vehicle: { vehicleTechTree: TechTree, vehicleOperator?: Countries }) {
  const fileName = countryIconFile[vehicle?.vehicleOperator ? vehicle.vehicleOperator : vehicle.vehicleTechTree] ?? techTreeFallback[vehicle.vehicleTechTree] ?? "country_usa.svg";
  if (vehicle.vehicleOperator === "Serbia") return `${WT_SKIN_BASE}/${fileName}.svg`;
  else return `${WT_SKIN_BASE}/country_${fileName}.svg`;
}